//
// Created by fresh on 1-5-24.
//

#ifndef STG_COMMUNICATION_SYSTEM_CONSTANTS_H
#define STG_COMMUNICATION_SYSTEM_CONSTANTS_H

#define DATETIME_MAX_LENGTH 21

// group ids
enum process_group_id {
    COORDINATOR_GROUP_ID = 0,
    SATELLITE_GROUP_ID = 1,
    GROUND_STATION_GROUP_ID = 2
};

// event/msg/envelope ids
enum event_t {
    ADD_METRIC = 0,
    ADD_STATUS = 1,
    ADD_ST_COORDINATES = 2,
    ADD_GS_COORDINATES = 3,
    STATUS_CHECK = 4,
    AVG_EARTH_TEMP = 5,
    SYNC = 6,
    PRINT = 7,
    TERMINATE = 8,
    FIND_MIN_DIST = 9,
    AVG_EARTH_TEMP_DONE = 10,
    CONNECT = 11,
    ACK = 12,
    LELECT_PROBE = 13,
    LELECT_REPLY = 14,
    START_LELECT_ST = 15,
    START_LELECT_GS = 16,
    LELECT_ST_DONE = 17,
    LELECT_GS_DONE = 18,
    LELECT_TERMINATE = 19,
    ST_LEADER = 20,
    GS_LEADER = 21,
    ELECT = 22,
    SYNC_DONE = 23,
    TERMINATE_LELECT_GS = 24
};
#endif //STG_COMMUNICATION_SYSTEM_CONSTANTS_H
