//
// Created by fresh on 1-5-24.
//

#ifndef STG_COMMUNICATION_SYSTEM_LEADER_ELECT_MANAGER_H
#define STG_COMMUNICATION_SYSTEM_LEADER_ELECT_MANAGER_H

enum elect_event_t {
    LELECT = 0,
    START_LELECT_ST = 1,
    LELECT_ST_DONE = 2,
    START_LELECT_GS = 3,
    LELECT_GS_DONE = 4
};
#endif //STG_COMMUNICATION_SYSTEM_LEADER_ELECT_MANAGER_H
